name: ${name}
main: ${main}

author: Arasple

api-version: 1.13
version: ${version}

lib-version: ${libVersion}
lib-download: ${libDownload}
loader-version: ${loaderVersion}

description: Advanced shortcuts

softdepend: [ PlaceholderAPI ]

built-time: ${built}
built-by: ${builder}
built-os: ${os}